name: "Testing"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  check-dist:
    name: Check dist directory
    uses: actions/reusable-workflows/.github/workflows/check-dist.yml@5e63e7aef083769958fc026fe8eea0241c0eb444
  test:
    name: Test
    uses: actions/reusable-workflows/.github/workflows/basic-validation.yml@5e63e7aef083769958fc026fe8eea0241c0eb444
